CREATE TABLE "companies"(
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR NOT NULL,
	"email" VARCHAR UNIQUE NOT NULL,
	"password" VARCHAR NOT NULL
);

CREATE TABLE "products"(
	"id" SERIAL PRIMARY KEY,
	"companyId" INTEGER NOT NULL REFERENCES "companies"(id) ON DELETE CASCADE ON UPDATE CASCADE,
	"name" VARCHAR NOT NULL,
	"quantity" INTEGER NOT NULL,
	"costPrice" FLOAT NOT NULL,
	"sellingPrice" FLOAT NOT NULL
);

CREATE TABLE "sales"(
	"id" SERIAL PRIMARY KEY,
	"companyId" INTEGER NOT NULL REFERENCES "companies"(id) ON DELETE CASCADE ON UPDATE CASCADE,
	"productId" INTEGER NOT NULL REFERENCES "products"(id) ON DELETE CASCADE ON UPDATE CASCADE,
	"quantity" INTEGER NOT NULL,
	"totalPrice" FLOAT NOT NULL,
	"date" DATE NOT NULL DEFAULT NOW()	
);

CREATE TABLE "expenses"(
	"id" SERIAL PRIMARY KEY,
	"companyId" INTEGER NOT NULL REFERENCES "companies"(id) ON DELETE CASCADE ON UPDATE CASCADE,
	"description" VARCHAR NOT NULL,
	"totalPrice" FLOAT NOT NULL,
	"date" DATE NOT NULL DEFAULT NOW()
);
